# Generated by Django 5.1.dev20240419123637 on 2024-07-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("producto_id", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                ("cantidad", models.IntegerField()),
                ("stock", models.IntegerField()),
                ("hash", models.CharField(max_length=64)),
                ("prev_hash", models.CharField(max_length=64)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
