# Generated by Django 5.1.dev20240419123637 on 2024-08-17 04:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="cliente",
            field=models.CharField(default="Desconocido", max_length=255),
        ),
        migrations.AddField(
            model_name="block",
            name="fecha",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
