# Generated by Django 5.1.dev20240419123637 on 2024-08-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0002_block_cliente_block_fecha"),
    ]

    operations = [
        migrations.RenameField(
            model_name="block",
            old_name="producto_id",
            new_name="orden_id",
        ),
    ]
