# Generated by Django 5.1.dev20240419123637 on 2024-08-27 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_pdf"),
        ("blockchain", "0003_rename_producto_id_block_orden_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="cliente",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="block",
            name="nombre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.product"
            ),
        ),
    ]
