# Generated by Django 5.1.dev20240419123637 on 2024-08-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0004_alter_block_cliente_alter_block_nombre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cadena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
