# Generated by Django 5.1.dev20240419123637 on 2024-09-02 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0005_cadena"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="cadena",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bloques",
                to="blockchain.cadena",
            ),
        ),
    ]
