# Generated by Django 5.1.dev20240419123637 on 2024-08-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Stationary", "Papelería"),
                    ("Electronics", "Electrónica"),
                    ("Food", "Alimentos"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
