# Generated by Django 5.1.dev20240419123637 on 2024-09-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="completado",
            field=models.BooleanField(default=False),
        ),
    ]
